### ISSUE TITLE
Moving tabs disrupts the tab layout.

### ISSUE THREAD

**Issue by anzuno** [carlotm/dotfiles#1]
Moving tabs disrupts the tab layout. In the attached image I am moving Wikipedia. Thanks.
OS: Windows8.1 Firefox98.
![qq](https://user-images.githubusercontent.com/69779167/158050137-7e27d74c-2249-4907-8cb9-9d947bdfd6c2.png)

**Comment by carlotm** [comment]
@anzuno 905ec7ff3c31de62f1f841b7b2b88f52c870db26 should fix that
